
services:
  postgres:
    image: postgres:15
    container_name: asterisk-postgres
    environment:
      POSTGRES_DB: asterisk
      POSTGRES_USER: asterisk
      POSTGRES_PASSWORD: asterisk
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - asterisk-net

volumes:
  postgres-data:

networks:
  asterisk-net:
    driver: bridge

