services:
  postgres:
    image: postgres:15
    container_name: asterisk-postgres
    environment:
      POSTGRES_DB: asterisk
      POSTGRES_USER: asterisk
      POSTGRES_PASSWORD: asterisk
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - asterisk-net

  asterisk:
    build: .
    container_name: asterisk-container
    volumes:
      - ./asterisk:/etc/asterisk
      - ./odbc.ini:/etc/odbc.ini
      - ./odbcinst.ini:/etc/odbcinst.ini
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5061:5061/udp"
      - "5061:5061/tcp"
      - "10000:20000/udp"
    networks:
      - asterisk-net
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  asterisk-net:
    driver: bridge
