version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: asterisk
      MYSQL_USER: asterisk
      MYSQL_PASSWORD: 12345678
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - asterisk_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    ports:
      - "8080:80"
    networks:
      - asterisk_net

volumes:
  mariadb_data:

networks:
  asterisk_net:                                 # Rede isolada
